import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Container;
import java.awt.FlowLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.LayoutManager;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRootPane;
import javax.swing.border.EmptyBorder;
import javax.swing.border.TitledBorder;

public final class class_610
  extends JDialog
{
  private static final long serialVersionUID = -2489180413668206755L;
  private final JPanel jdField_field_895_of_type_JavaxSwingJPanel = new JPanel();
  private short jdField_field_895_of_type_Short = -1;
  private String jdField_field_895_of_type_JavaLangString = "";
  private short field_896 = -1;
  private int jdField_field_895_of_type_Int = 1;
  private short field_897 = -1;
  private Class jdField_field_895_of_type_JavaLangClass = null;
  
  public class_610(JFrame paramJFrame, class_684 paramclass_684)
  {
    super(paramJFrame, true);
    setBounds(100, 100, 491, 453);
    getContentPane().setLayout(new BorderLayout());
    this.jdField_field_895_of_type_JavaxSwingJPanel.setBorder(new EmptyBorder(5, 5, 5, 5));
    getContentPane().add(this.jdField_field_895_of_type_JavaxSwingJPanel, "Center");
    (localObject1 = new GridBagLayout()).columnWidths = new int[] { 0 };
    ((GridBagLayout)localObject1).rowHeights = new int[] { 0, 0, 0, 0, 0 };
    ((GridBagLayout)localObject1).columnWeights = new double[] { 1.0D };
    ((GridBagLayout)localObject1).rowWeights = new double[] { 1.0D, 0.0D, 0.0D, 0.0D, 1.0D };
    this.jdField_field_895_of_type_JavaxSwingJPanel.setLayout((LayoutManager)localObject1);
    (localObject1 = new JPanel()).setBorder(new TitledBorder(null, "Block Id", 4, 2, null, null));
    (localObject2 = new GridBagConstraints()).fill = 2;
    ((GridBagConstraints)localObject2).insets = new Insets(10, 0, 10, 0);
    ((GridBagConstraints)localObject2).weightx = 1.0D;
    ((GridBagConstraints)localObject2).anchor = 18;
    ((GridBagConstraints)localObject2).gridx = 0;
    ((GridBagConstraints)localObject2).gridy = 0;
    this.jdField_field_895_of_type_JavaxSwingJPanel.add((Component)localObject1, localObject2);
    (localObject2 = new GridBagLayout()).columnWidths = new int[] { 0, 0, 0 };
    ((GridBagLayout)localObject2).rowHeights = new int[] { 0, 0 };
    ((GridBagLayout)localObject2).columnWeights = new double[] { 0.0D, 0.0D, 4.9E-324D };
    ((GridBagLayout)localObject2).rowWeights = new double[] { 0.0D, 4.9E-324D };
    ((JPanel)localObject1).setLayout((LayoutManager)localObject2);
    Object localObject2 = new JLabel("----");
    (localObject3 = new GridBagConstraints()).insets = new Insets(5, 5, 5, 5);
    ((GridBagConstraints)localObject3).gridx = 0;
    ((GridBagConstraints)localObject3).gridy = 0;
    ((JPanel)localObject1).add((Component)localObject2, localObject3);
    (localObject3 = new JButton("Pick")).addActionListener(new class_608(this, paramJFrame, (JLabel)localObject2));
    GridBagConstraints localGridBagConstraints;
    (localGridBagConstraints = new GridBagConstraints()).weightx = 1.0D;
    localGridBagConstraints.anchor = 13;
    localGridBagConstraints.gridx = 1;
    localGridBagConstraints.gridy = 0;
    ((JPanel)localObject1).add((Component)localObject3, localGridBagConstraints);
    (localObject1 = new JPanel()).setBorder(new TitledBorder(null, "Texture ID", 4, 2, null, null));
    (localObject2 = new GridBagConstraints()).anchor = 17;
    ((GridBagConstraints)localObject2).insets = new Insets(10, 0, 10, 0);
    ((GridBagConstraints)localObject2).fill = 1;
    ((GridBagConstraints)localObject2).gridx = 0;
    ((GridBagConstraints)localObject2).gridy = 1;
    this.jdField_field_895_of_type_JavaxSwingJPanel.add((Component)localObject1, localObject2);
    (localObject2 = new GridBagLayout()).columnWidths = new int[] { 0, 0, 0 };
    ((GridBagLayout)localObject2).rowHeights = new int[] { 0, 0 };
    ((GridBagLayout)localObject2).columnWeights = new double[] { 0.0D, 0.0D, 4.9E-324D };
    ((GridBagLayout)localObject2).rowWeights = new double[] { 0.0D, 4.9E-324D };
    ((JPanel)localObject1).setLayout((LayoutManager)localObject2);
    localObject2 = new JLabel("----");
    (localObject3 = new GridBagConstraints()).insets = new Insets(5, 5, 0, 5);
    ((GridBagConstraints)localObject3).gridx = 0;
    ((GridBagConstraints)localObject3).gridy = 0;
    ((JPanel)localObject1).add((Component)localObject2, localObject3);
    Object localObject3 = new JButton("Pick");
    (localGridBagConstraints = new GridBagConstraints()).weightx = 1.0D;
    localGridBagConstraints.anchor = 13;
    localGridBagConstraints.gridx = 1;
    localGridBagConstraints.gridy = 0;
    ((JPanel)localObject1).add((Component)localObject3, localGridBagConstraints);
    ((JButton)localObject3).addActionListener(new class_606(this, paramJFrame, (JLabel)localObject2));
    (localObject1 = new JPanel()).setBorder(new TitledBorder(null, "Icon ID", 4, 2, null, null));
    (localObject2 = new GridBagConstraints()).fill = 1;
    ((GridBagConstraints)localObject2).anchor = 18;
    ((GridBagConstraints)localObject2).insets = new Insets(10, 0, 10, 0);
    ((GridBagConstraints)localObject2).gridx = 0;
    ((GridBagConstraints)localObject2).gridy = 2;
    this.jdField_field_895_of_type_JavaxSwingJPanel.add((Component)localObject1, localObject2);
    (localObject2 = new GridBagLayout()).columnWidths = new int[] { 0, 0, 0 };
    ((GridBagLayout)localObject2).rowHeights = new int[] { 0, 0 };
    ((GridBagLayout)localObject2).columnWeights = new double[] { 0.0D, 0.0D, 4.9E-324D };
    ((GridBagLayout)localObject2).rowWeights = new double[] { 0.0D, 4.9E-324D };
    ((JPanel)localObject1).setLayout((LayoutManager)localObject2);
    localObject2 = new JLabel("----");
    (localObject3 = new GridBagConstraints()).insets = new Insets(5, 5, 0, 5);
    ((GridBagConstraints)localObject3).gridx = 0;
    ((GridBagConstraints)localObject3).gridy = 0;
    ((JPanel)localObject1).add((Component)localObject2, localObject3);
    localObject3 = new JButton("Pick");
    (localGridBagConstraints = new GridBagConstraints()).weightx = 1.0D;
    localGridBagConstraints.anchor = 13;
    localGridBagConstraints.gridx = 1;
    localGridBagConstraints.gridy = 0;
    ((JButton)localObject3).addActionListener(new class_618(this, paramJFrame, (JLabel)localObject2));
    ((JPanel)localObject1).add((Component)localObject3, localGridBagConstraints);
    localObject3 = new JButton("Generate");
    (localGridBagConstraints = new GridBagConstraints()).weightx = 1.0D;
    localGridBagConstraints.anchor = 13;
    localGridBagConstraints.gridx = 2;
    localGridBagConstraints.gridy = 0;
    ((JButton)localObject3).addActionListener(new class_616(this, (JLabel)localObject2));
    ((JPanel)localObject1).add((Component)localObject3, localGridBagConstraints);
    (localObject1 = new JPanel()).setBorder(new TitledBorder(null, "Name", 4, 2, null, null));
    (localObject2 = new GridBagConstraints()).fill = 2;
    ((GridBagConstraints)localObject2).anchor = 18;
    ((GridBagConstraints)localObject2).weightx = 1.0D;
    ((GridBagConstraints)localObject2).insets = new Insets(10, 0, 10, 0);
    ((GridBagConstraints)localObject2).gridx = 0;
    ((GridBagConstraints)localObject2).gridy = 3;
    this.jdField_field_895_of_type_JavaxSwingJPanel.add((Component)localObject1, localObject2);
    (localObject2 = new GridBagLayout()).columnWidths = new int[] { 0, 0, 0 };
    ((GridBagLayout)localObject2).rowHeights = new int[] { 0, 0 };
    ((GridBagLayout)localObject2).columnWeights = new double[] { 0.0D, 0.0D, 4.9E-324D };
    ((GridBagLayout)localObject2).rowWeights = new double[] { 0.0D, 4.9E-324D };
    ((JPanel)localObject1).setLayout((LayoutManager)localObject2);
    localObject2 = new JLabel("----");
    (localObject3 = new GridBagConstraints()).insets = new Insets(5, 5, 0, 5);
    ((GridBagConstraints)localObject3).gridx = 0;
    ((GridBagConstraints)localObject3).gridy = 0;
    ((JPanel)localObject1).add((Component)localObject2, localObject3);
    localObject3 = new JButton("Pick");
    (localGridBagConstraints = new GridBagConstraints()).weightx = 1.0D;
    localGridBagConstraints.anchor = 13;
    localGridBagConstraints.gridx = 1;
    localGridBagConstraints.gridy = 0;
    ((JPanel)localObject1).add((Component)localObject3, localGridBagConstraints);
    ((JButton)localObject3).addActionListener(new class_614(this, paramJFrame, (JLabel)localObject2));
    (localObject3 = new JPanel()).setBorder(new TitledBorder(null, "Category", 4, 2, null, null));
    (localGridBagConstraints = new GridBagConstraints()).fill = 1;
    localGridBagConstraints.gridx = 0;
    localGridBagConstraints.gridy = 4;
    this.jdField_field_895_of_type_JavaxSwingJPanel.add((Component)localObject3, localGridBagConstraints);
    (localObject1 = new GridBagLayout()).columnWidths = new int[] { 0, 0, 0 };
    ((GridBagLayout)localObject1).rowHeights = new int[] { 0, 0 };
    ((GridBagLayout)localObject1).columnWeights = new double[] { 0.0D, 0.0D, 4.9E-324D };
    ((GridBagLayout)localObject1).rowWeights = new double[] { 0.0D, 4.9E-324D };
    ((JPanel)localObject3).setLayout((LayoutManager)localObject1);
    Object localObject1 = new JLabel("----");
    (localObject2 = new GridBagConstraints()).insets = new Insets(5, 5, 0, 5);
    ((GridBagConstraints)localObject2).gridx = 0;
    ((GridBagConstraints)localObject2).gridy = 0;
    ((JPanel)localObject3).add((Component)localObject1, localObject2);
    localObject2 = new JButton("Pick");
    (localGridBagConstraints = new GridBagConstraints()).weightx = 1.0D;
    localGridBagConstraints.anchor = 13;
    localGridBagConstraints.gridx = 1;
    localGridBagConstraints.gridy = 0;
    ((JPanel)localObject3).add((Component)localObject2, localGridBagConstraints);
    ((JButton)localObject2).addActionListener(new class_612(this, paramJFrame, (JLabel)localObject1));
    (localObject1 = new JPanel()).setLayout(new FlowLayout(2));
    getContentPane().add((Component)localObject1, "South");
    (localObject2 = new JButton("OK")).setActionCommand("OK");
    ((JPanel)localObject1).add((Component)localObject2);
    getRootPane().setDefaultButton((JButton)localObject2);
    ((JButton)localObject2).addActionListener(new class_623(this, paramJFrame, paramclass_684));
    (localObject2 = new JButton("Cancel")).setActionCommand("Cancel");
    ((JPanel)localObject1).add((Component)localObject2);
    ((JButton)localObject2).addActionListener(new class_621(this));
  }
}


/* Location:           C:\Users\Raul\Desktop\StarMadeDec\StarMadeR.zip
 * Qualified Name:     class_610
 * JD-Core Version:    0.7.0-SNAPSHOT-20130630
 */