import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.LayoutManager;
import java.util.ArrayList;
import java.util.Observer;
import javax.swing.ButtonGroup;
import javax.swing.ComboBoxEditor;
import javax.swing.JButton;
import javax.swing.JCheckBoxMenuItem;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JRootPane;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.border.EmptyBorder;
import javax.swing.border.EtchedBorder;
import javax.swing.border.TitledBorder;

public final class class_489
  extends JFrame
{
  private static final long serialVersionUID = 778151002712218127L;
  private final JPanel jdField_field_805_of_type_JavaxSwingJPanel = new JPanel();
  private JTextField jdField_field_805_of_type_JavaxSwingJTextField;
  private JComboBox jdField_field_805_of_type_JavaxSwingJComboBox;
  private boolean jdField_field_805_of_type_Boolean;
  private class_579 jdField_field_805_of_type_Class_579;
  private ArrayList jdField_field_805_of_type_JavaUtilArrayList;
  private final ButtonGroup jdField_field_805_of_type_JavaxSwingButtonGroup = new ButtonGroup();
  private JRadioButton jdField_field_805_of_type_JavaxSwingJRadioButton;
  private JRadioButton jdField_field_806_of_type_JavaxSwingJRadioButton;
  private JComboBox jdField_field_806_of_type_JavaxSwingJComboBox;
  private JScrollPane jdField_field_805_of_type_JavaxSwingJScrollPane;
  private JButton jdField_field_805_of_type_JavaxSwingJButton;
  
  public class_489(Observer paramObserver, ArrayList paramArrayList)
  {
    super("StarMade alpha " + class_1266.jdField_field_1446_of_type_Float + " (" + class_1266.jdField_field_1446_of_type_JavaLangString + ")");
    if (paramArrayList.isEmpty()) {
      paramArrayList.add(new class_899("localhost", 4242, ""));
    }
    addWindowListener(new class_487());
    this.jdField_field_805_of_type_JavaUtilArrayList = paramArrayList;
    setDefaultCloseOperation(3);
    setAlwaysOnTop(false);
    setUndecorated(false);
    this.jdField_field_805_of_type_Class_579 = new class_579(this, (byte)0);
    this.jdField_field_805_of_type_Class_579.addObserver(paramObserver);
    setTitle("Connection Setup");
    setBounds(50, 50, 483, 730);
    getContentPane().setLayout(new BorderLayout());
    this.jdField_field_805_of_type_JavaxSwingJPanel.setBorder(new EmptyBorder(5, 5, 5, 5));
    getContentPane().add(this.jdField_field_805_of_type_JavaxSwingJPanel, "North");
    (paramObserver = new GridBagLayout()).columnWidths = new int[] { 268, 0 };
    paramObserver.rowHeights = new int[] { 0, 0, 0, 0 };
    paramObserver.columnWeights = new double[] { 1.0D, 4.9E-324D };
    paramObserver.rowWeights = new double[] { 0.0D, 0.0D, 0.0D, 0.0D };
    this.jdField_field_805_of_type_JavaxSwingJPanel.setLayout(paramObserver);
    paramObserver = new JPanel();
    (localObject1 = new GridBagConstraints()).insets = new Insets(5, 0, 15, 0);
    ((GridBagConstraints)localObject1).anchor = 17;
    ((GridBagConstraints)localObject1).gridx = 0;
    ((GridBagConstraints)localObject1).gridy = 0;
    this.jdField_field_805_of_type_JavaxSwingJPanel.add(paramObserver, localObject1);
    (localObject1 = new GridBagLayout()).columnWidths = new int[] { 322, 46, 0 };
    ((GridBagLayout)localObject1).rowHeights = new int[] { 40, 0 };
    ((GridBagLayout)localObject1).columnWeights = new double[] { 0.0D, 0.0D, 4.9E-324D };
    ((GridBagLayout)localObject1).rowWeights = new double[] { 0.0D, 4.9E-324D };
    paramObserver.setLayout((LayoutManager)localObject1);
    (localObject1 = new JLabel("StarMade alpha V" + class_1266.jdField_field_1446_of_type_Float)).setFont(new Font("Ubuntu-Title", 0, 30));
    (localObject2 = new GridBagConstraints()).anchor = 18;
    ((GridBagConstraints)localObject2).insets = new Insets(0, 0, 0, 5);
    ((GridBagConstraints)localObject2).gridx = 0;
    ((GridBagConstraints)localObject2).gridy = 0;
    paramObserver.add((Component)localObject1, localObject2);
    (paramObserver = new JPanel()).setBorder(new EtchedBorder(1, null, null));
    (localObject1 = new GridBagConstraints()).anchor = 18;
    ((GridBagConstraints)localObject1).insets = new Insets(5, 0, 5, 0);
    ((GridBagConstraints)localObject1).gridx = 0;
    ((GridBagConstraints)localObject1).gridy = 1;
    this.jdField_field_805_of_type_JavaxSwingJPanel.add(paramObserver, localObject1);
    (localObject1 = new GridBagLayout()).columnWidths = new int[] { 0, 170, 0 };
    ((GridBagLayout)localObject1).rowHeights = new int[] { 20, 0 };
    ((GridBagLayout)localObject1).columnWeights = new double[] { 0.0D, 0.0D, 0.0D };
    ((GridBagLayout)localObject1).rowWeights = new double[] { 0.0D, 0.0D };
    paramObserver.setLayout((LayoutManager)localObject1);
    (localObject1 = new JLabel("In-Game Name")).setFont(new Font("Arial", 1, 12));
    (localObject2 = new GridBagConstraints()).insets = new Insets(0, 5, 5, 20);
    ((GridBagConstraints)localObject2).anchor = 13;
    ((GridBagConstraints)localObject2).gridx = 0;
    ((GridBagConstraints)localObject2).gridy = 0;
    paramObserver.add((Component)localObject1, localObject2);
    this.jdField_field_805_of_type_JavaxSwingJTextField = new JTextField();
    this.jdField_field_805_of_type_JavaxSwingJTextField.setHorizontalAlignment(0);
    this.jdField_field_805_of_type_JavaxSwingJTextField.setToolTipText("Login Name");
    (localObject1 = new GridBagConstraints()).insets = new Insets(0, 0, 5, 5);
    ((GridBagConstraints)localObject1).fill = 2;
    ((GridBagConstraints)localObject1).gridx = 1;
    ((GridBagConstraints)localObject1).gridy = 0;
    paramObserver.add(this.jdField_field_805_of_type_JavaxSwingJTextField, localObject1);
    this.jdField_field_805_of_type_JavaxSwingJTextField.setColumns(30);
    (localObject2 = new JButton("Uplink To Star-Made.org")).addActionListener(new class_565());
    (localObject3 = new GridBagConstraints()).anchor = 13;
    ((GridBagConstraints)localObject3).insets = new Insets(0, 0, 5, 0);
    ((GridBagConstraints)localObject3).gridx = 2;
    ((GridBagConstraints)localObject3).gridy = 0;
    paramObserver.add((Component)localObject2, localObject3);
    Object localObject2 = new JLabel("Uplink to protect your player file on multiplayer servers.");
    (localObject3 = new GridBagConstraints()).gridwidth = 3;
    ((GridBagConstraints)localObject3).insets = new Insets(0, 0, 0, 5);
    ((GridBagConstraints)localObject3).gridx = 0;
    ((GridBagConstraints)localObject3).gridy = 1;
    paramObserver.add((Component)localObject2, localObject3);
    if ((paramArrayList != null) && (!paramArrayList.isEmpty())) {
      this.jdField_field_805_of_type_JavaxSwingJTextField.setText(((class_899)paramArrayList.get(paramArrayList.size() - 1)).field_1126);
    }
    (paramObserver = new JPanel()).setBorder(new TitledBorder(UIManager.getBorder("TitledBorder.border"), "Game", 4, 2, null, new Color(0, 0, 0)));
    (localObject1 = new GridBagConstraints()).fill = 1;
    ((GridBagConstraints)localObject1).gridx = 0;
    ((GridBagConstraints)localObject1).gridy = 2;
    this.jdField_field_805_of_type_JavaxSwingJPanel.add(paramObserver, localObject1);
    (localObject1 = new GridBagLayout()).columnWidths = new int[] { 0 };
    ((GridBagLayout)localObject1).rowHeights = new int[] { 0, 0 };
    ((GridBagLayout)localObject1).columnWeights = new double[] { 0.0D };
    ((GridBagLayout)localObject1).rowWeights = new double[] { 0.0D, 0.0D };
    paramObserver.setLayout((LayoutManager)localObject1);
    (localObject1 = new JPanel()).setBorder(new TitledBorder(null, "Single Player", 4, 2, null, null));
    (localObject2 = new GridBagConstraints()).weightx = 1.0D;
    ((GridBagConstraints)localObject2).anchor = 18;
    ((GridBagConstraints)localObject2).insets = new Insets(0, 0, 5, 5);
    ((GridBagConstraints)localObject2).fill = 2;
    ((GridBagConstraints)localObject2).gridx = 0;
    ((GridBagConstraints)localObject2).gridy = 0;
    paramObserver.add((Component)localObject1, localObject2);
    (localObject3 = new GridBagLayout()).columnWidths = new int[] { 21, 0, 130, 0 };
    ((GridBagLayout)localObject3).rowHeights = new int[] { 21, 0 };
    ((GridBagLayout)localObject3).columnWeights = new double[] { 0.0D, 0.0D, 0.0D, 4.9E-324D };
    ((GridBagLayout)localObject3).rowWeights = new double[] { 0.0D, 4.9E-324D };
    ((JPanel)localObject1).setLayout((LayoutManager)localObject3);
    this.jdField_field_805_of_type_JavaxSwingJRadioButton = new JRadioButton("");
    (localObject2 = new GridBagConstraints()).anchor = 17;
    ((GridBagConstraints)localObject2).insets = new Insets(0, 0, 0, 5);
    ((GridBagConstraints)localObject2).gridx = 0;
    ((GridBagConstraints)localObject2).gridy = 0;
    ((JPanel)localObject1).add(this.jdField_field_805_of_type_JavaxSwingJRadioButton, localObject2);
    this.jdField_field_805_of_type_JavaxSwingButtonGroup.add(this.jdField_field_805_of_type_JavaxSwingJRadioButton);
    this.jdField_field_805_of_type_JavaxSwingJRadioButton.setSelected(class_949.field_1217.a4().equals("Single Player"));
    this.jdField_field_805_of_type_JavaxSwingJRadioButton.addChangeListener(new class_567(this));
    localObject2 = new JLabel("Game Mode");
    (localObject3 = new GridBagConstraints()).insets = new Insets(0, 0, 0, 5);
    ((GridBagConstraints)localObject3).anchor = 13;
    ((GridBagConstraints)localObject3).gridx = 1;
    ((GridBagConstraints)localObject3).gridy = 0;
    ((JPanel)localObject1).add((Component)localObject2, localObject3);
    this.jdField_field_806_of_type_JavaxSwingJComboBox = new JComboBox(new class_1341(class_949.field_1218));
    (localObject2 = new GridBagConstraints()).gridx = 2;
    ((GridBagConstraints)localObject2).gridy = 0;
    ((JPanel)localObject1).add(this.jdField_field_806_of_type_JavaxSwingJComboBox, localObject2);
    this.jdField_field_805_of_type_JavaxSwingJComboBox = new JComboBox(new class_581(this, (byte)0));
    (localObject2 = new JPanel()).setBorder(new TitledBorder(UIManager.getBorder("TitledBorder.border"), "MultiPlayer", 4, 2, null, new Color(0, 0, 0)));
    (localObject3 = new GridBagConstraints()).weightx = 1.0D;
    ((GridBagConstraints)localObject3).anchor = 18;
    ((GridBagConstraints)localObject3).insets = new Insets(0, 0, 5, 5);
    ((GridBagConstraints)localObject3).gridx = 0;
    ((GridBagConstraints)localObject3).gridy = 1;
    paramObserver.add((Component)localObject2, localObject3);
    (paramObserver = new GridBagLayout()).columnWidths = new int[] { 0, 0, 0 };
    paramObserver.rowHeights = new int[] { 0, 0, 0 };
    paramObserver.columnWeights = new double[] { 1.0D, 0.0D, 4.9E-324D };
    paramObserver.rowWeights = new double[] { 0.0D, 1.0D, 4.9E-324D };
    ((JPanel)localObject2).setLayout(paramObserver);
    this.jdField_field_806_of_type_JavaxSwingJRadioButton = new JRadioButton("");
    (paramObserver = new GridBagConstraints()).anchor = 17;
    paramObserver.insets = new Insets(0, 0, 5, 0);
    paramObserver.gridx = 0;
    paramObserver.gridy = 0;
    ((JPanel)localObject2).add(this.jdField_field_806_of_type_JavaxSwingJRadioButton, paramObserver);
    this.jdField_field_806_of_type_JavaxSwingJRadioButton.setSelected(class_949.field_1217.a4().equals("Multi Player"));
    this.jdField_field_805_of_type_JavaxSwingButtonGroup.add(this.jdField_field_806_of_type_JavaxSwingJRadioButton);
    paramObserver = new JPanel();
    (localObject1 = new GridBagConstraints()).insets = new Insets(0, 10, 0, 0);
    ((GridBagConstraints)localObject1).weightx = 100.0D;
    ((GridBagConstraints)localObject1).anchor = 18;
    ((GridBagConstraints)localObject1).gridx = 1;
    ((GridBagConstraints)localObject1).gridy = 0;
    ((JPanel)localObject2).add(paramObserver, localObject1);
    (localObject1 = new GridBagLayout()).columnWidths = new int[] { 52, 0, 206, 0 };
    ((GridBagLayout)localObject1).rowHeights = new int[] { 20, 0 };
    ((GridBagLayout)localObject1).columnWeights = new double[] { 0.0D, 1.0D, 0.0D, 4.9E-324D };
    ((GridBagLayout)localObject1).rowWeights = new double[] { 1.0D, 4.9E-324D };
    paramObserver.setLayout((LayoutManager)localObject1);
    Object localObject1 = new JLabel(" Host:Port  ");
    (localObject2 = new GridBagConstraints()).ipady = 1;
    ((GridBagConstraints)localObject2).ipadx = 1;
    ((GridBagConstraints)localObject2).fill = 2;
    ((GridBagConstraints)localObject2).insets = new Insets(0, 0, 0, 5);
    ((GridBagConstraints)localObject2).gridx = 0;
    ((GridBagConstraints)localObject2).gridy = 0;
    paramObserver.add((Component)localObject1, localObject2);
    this.jdField_field_805_of_type_JavaxSwingJComboBox.setEditable(true);
    this.jdField_field_805_of_type_JavaxSwingJComboBox.setSelectedIndex(paramArrayList.size() - 1);
    this.jdField_field_805_of_type_JavaxSwingJComboBox.getEditor().setItem(((class_899)paramArrayList.get(paramArrayList.size() - 1)).toString());
    (localObject1 = new GridBagConstraints()).fill = 2;
    ((GridBagConstraints)localObject1).anchor = 11;
    ((GridBagConstraints)localObject1).gridx = 2;
    ((GridBagConstraints)localObject1).gridy = 0;
    paramObserver.add(this.jdField_field_805_of_type_JavaxSwingJComboBox, localObject1);
    this.jdField_field_805_of_type_JavaxSwingJScrollPane = new JScrollPane();
    (localObject2 = new GridBagConstraints()).weighty = 1.0D;
    ((GridBagConstraints)localObject2).weightx = 1.0D;
    ((GridBagConstraints)localObject2).fill = 1;
    ((GridBagConstraints)localObject2).gridx = 0;
    ((GridBagConstraints)localObject2).gridy = 3;
    this.jdField_field_805_of_type_JavaxSwingJPanel.add(this.jdField_field_805_of_type_JavaxSwingJScrollPane, localObject2);
    Object localObject3 = new class_585();
    this.jdField_field_805_of_type_JavaxSwingJScrollPane.setViewportView((Component)localObject3);
    ((class_585)localObject3).setBorder(new TitledBorder(null, "Settings", 4, 2, null, null));
    (localObject2 = new JPanel()).setLayout(new FlowLayout(2));
    getContentPane().add((Component)localObject2, "South");
    localObject3 = this;
    this.jdField_field_805_of_type_JavaxSwingJButton = new JButton("OK");
    this.jdField_field_805_of_type_JavaxSwingJButton.setMultiClickThreshhold(1000L);
    this.jdField_field_805_of_type_JavaxSwingJButton.addActionListener(new class_569(this, (JFrame)localObject3));
    this.jdField_field_805_of_type_JavaxSwingJButton.setActionCommand("OK");
    ((JPanel)localObject2).add(this.jdField_field_805_of_type_JavaxSwingJButton);
    getRootPane().setDefaultButton(this.jdField_field_805_of_type_JavaxSwingJButton);
    (paramObserver = new JButton("Cancel")).addActionListener(new class_571());
    paramObserver.setActionCommand("Cancel");
    ((JPanel)localObject2).add(paramObserver);
    localObject2 = new JMenuBar();
    setJMenuBar((JMenuBar)localObject2);
    localObject3 = new JMenu("Uplink");
    ((JMenuBar)localObject2).add((JMenu)localObject3);
    (paramObserver = new JMenuItem("Login to Star-Made.org")).addActionListener(new class_587());
    ((JMenu)localObject3).add(paramObserver);
    localObject3 = new JMenu("Settings");
    ((JMenuBar)localObject2).add((JMenu)localObject3);
    (paramObserver = new JCheckBoxMenuItem("Show Advanced Settings")).addActionListener(new class_589(this, paramObserver));
    ((JMenu)localObject3).add(paramObserver);
    localObject3 = new JMenu("Tools");
    ((JMenuBar)localObject2).add((JMenu)localObject3);
    (paramObserver = new JMenuItem("Open Ship Catalog Manager")).addActionListener(new class_591(this));
    ((JMenu)localObject3).add(paramObserver);
    (paramObserver = new JMenuItem("Migrate Database (for older Versions)")).addActionListener(new class_593(this));
    ((JMenu)localObject3).add(paramObserver);
    (paramObserver = new JMenuItem("Reset Universe")).addActionListener(new class_510(this));
    ((JMenu)localObject3).add(paramObserver);
    (paramObserver = new JMenuItem("View Index Database")).addActionListener(new class_508());
    ((JMenu)localObject3).add(paramObserver);
    (paramObserver = new JMenuItem("Start StarMote Remote Tool")).addActionListener(new class_506());
    ((JMenu)localObject3).add(paramObserver);
    localObject3 = new JMenu("Crash & Bug Report");
    ((JMenuBar)localObject2).add((JMenu)localObject3);
    (paramObserver = new JMenuItem("Launch Report Tool")).addActionListener(new class_504());
    ((JMenu)localObject3).add(paramObserver);
    localObject3 = new JMenu("Modding");
    ((JMenuBar)localObject2).add((JMenu)localObject3);
    (paramObserver = new JMenuItem("Block Editor")).addActionListener(new class_574());
    ((JMenu)localObject3).add(paramObserver);
    (paramObserver = new JMenuItem("Custom Skin")).addActionListener(new class_578(this));
    ((JMenu)localObject3).add(paramObserver);
  }
}


/* Location:           C:\Users\Raul\Desktop\StarMadeDec\StarMadeR.zip
 * Qualified Name:     class_489
 * JD-Core Version:    0.7.0-SNAPSHOT-20130630
 */