import java.awt.Component;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.LayoutManager;
import javax.swing.JLabel;
import javax.swing.JPanel;

public final class class_583
  extends JPanel
{
  private static final long serialVersionUID = -7527303857041337040L;
  
  public class_583()
  {
    (localObject1 = new GridBagLayout()).columnWidths = new int[] { 0, 0, 0 };
    ((GridBagLayout)localObject1).rowHeights = new int[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
    ((GridBagLayout)localObject1).columnWeights = new double[] { 0.0D, 1.0D, 4.9E-324D };
    ((GridBagLayout)localObject1).rowWeights = new double[] { 0.0D, 0.0D, 0.0D, 0.0D, 0.0D, 0.0D, 0.0D, 0.0D, 0.0D, 0.0D, 0.0D, 0.0D, 0.0D, 0.0D, 0.0D, 0.0D, 0.0D, 0.0D, 0.0D, 0.0D, 4.9E-324D };
    setLayout((LayoutManager)localObject1);
    Object localObject1 = new JLabel(" Resolution: ");
    (localObject2 = new GridBagConstraints()).insets = new Insets(0, 5, 5, 5);
    ((GridBagConstraints)localObject2).anchor = 17;
    ((GridBagConstraints)localObject2).gridx = 0;
    ((GridBagConstraints)localObject2).gridy = 0;
    add((Component)localObject1, localObject2);
    Object localObject2 = new class_537(class_949.field_1176);
    ((JLabel)localObject1).setLabelFor((Component)localObject2);
    (localObject1 = new GridBagConstraints()).insets = new Insets(0, 0, 5, 0);
    ((GridBagConstraints)localObject1).fill = 2;
    ((GridBagConstraints)localObject1).gridx = 1;
    ((GridBagConstraints)localObject1).gridy = 0;
    add((Component)localObject2, localObject1);
    localObject1 = new JLabel(" AntiAliasing samples: ");
    (localObject2 = new GridBagConstraints()).insets = new Insets(0, 5, 5, 5);
    ((GridBagConstraints)localObject2).anchor = 17;
    ((GridBagConstraints)localObject2).gridx = 0;
    ((GridBagConstraints)localObject2).gridy = 1;
    add((Component)localObject1, localObject2);
    localObject2 = new class_537(class_949.field_1238);
    ((JLabel)localObject1).setLabelFor((Component)localObject2);
    (localObject1 = new GridBagConstraints()).insets = new Insets(0, 0, 5, 0);
    ((GridBagConstraints)localObject1).fill = 2;
    ((GridBagConstraints)localObject1).gridx = 1;
    ((GridBagConstraints)localObject1).gridy = 1;
    add((Component)localObject2, localObject1);
    localObject1 = new JLabel(" Bloom: ");
    (localObject2 = new GridBagConstraints()).insets = new Insets(0, 5, 5, 5);
    ((GridBagConstraints)localObject2).anchor = 17;
    ((GridBagConstraints)localObject2).gridx = 0;
    ((GridBagConstraints)localObject2).gridy = 2;
    add((Component)localObject1, localObject2);
    localObject2 = new class_537(class_949.field_1240);
    ((JLabel)localObject1).setLabelFor((Component)localObject2);
    (localObject1 = new GridBagConstraints()).insets = new Insets(0, 0, 5, 0);
    ((GridBagConstraints)localObject1).fill = 2;
    ((GridBagConstraints)localObject1).gridx = 1;
    ((GridBagConstraints)localObject1).gridy = 2;
    add((Component)localObject2, localObject1);
    localObject1 = new JLabel(" View Distance: ");
    (localObject2 = new GridBagConstraints()).insets = new Insets(0, 5, 5, 5);
    ((GridBagConstraints)localObject2).anchor = 17;
    ((GridBagConstraints)localObject2).gridx = 0;
    ((GridBagConstraints)localObject2).gridy = 3;
    add((Component)localObject1, localObject2);
    localObject2 = new class_537(class_949.field_1179);
    ((JLabel)localObject1).setLabelFor((Component)localObject2);
    (localObject1 = new GridBagConstraints()).insets = new Insets(0, 0, 5, 0);
    ((GridBagConstraints)localObject1).fill = 2;
    ((GridBagConstraints)localObject1).gridx = 1;
    ((GridBagConstraints)localObject1).gridy = 3;
    add((Component)localObject2, localObject1);
    localObject1 = new JLabel(" Vertical Synch: ");
    (localObject2 = new GridBagConstraints()).insets = new Insets(0, 5, 5, 5);
    ((GridBagConstraints)localObject2).anchor = 17;
    ((GridBagConstraints)localObject2).gridx = 0;
    ((GridBagConstraints)localObject2).gridy = 4;
    add((Component)localObject1, localObject2);
    localObject2 = new class_537(class_949.field_1178);
    ((JLabel)localObject1).setLabelFor((Component)localObject2);
    (localObject1 = new GridBagConstraints()).insets = new Insets(0, 0, 5, 0);
    ((GridBagConstraints)localObject1).fill = 2;
    ((GridBagConstraints)localObject1).gridx = 1;
    ((GridBagConstraints)localObject1).gridy = 4;
    add((Component)localObject2, localObject1);
    localObject1 = new JLabel(" Fullscreen: ");
    (localObject2 = new GridBagConstraints()).anchor = 17;
    ((GridBagConstraints)localObject2).insets = new Insets(0, 5, 5, 5);
    ((GridBagConstraints)localObject2).gridx = 0;
    ((GridBagConstraints)localObject2).gridy = 5;
    add((Component)localObject1, localObject2);
    localObject2 = new class_537(class_949.field_1177);
    ((JLabel)localObject1).setLabelFor((Component)localObject2);
    (localObject1 = new GridBagConstraints()).insets = new Insets(0, 0, 5, 0);
    ((GridBagConstraints)localObject1).fill = 2;
    ((GridBagConstraints)localObject1).gridx = 1;
    ((GridBagConstraints)localObject1).gridy = 5;
    add((Component)localObject2, localObject1);
    localObject1 = new JLabel(" Fixed Framerate: ");
    (localObject2 = new GridBagConstraints()).anchor = 17;
    ((GridBagConstraints)localObject2).insets = new Insets(0, 5, 5, 5);
    ((GridBagConstraints)localObject2).gridx = 0;
    ((GridBagConstraints)localObject2).gridy = 6;
    add((Component)localObject1, localObject2);
    localObject2 = new class_537(class_949.field_1202);
    ((JLabel)localObject1).setLabelFor((Component)localObject2);
    (localObject1 = new GridBagConstraints()).insets = new Insets(0, 0, 5, 0);
    ((GridBagConstraints)localObject1).fill = 2;
    ((GridBagConstraints)localObject1).gridx = 1;
    ((GridBagConstraints)localObject1).gridy = 6;
    add((Component)localObject2, localObject1);
    localObject1 = new JLabel(" Max Segments in Graphics Memory: ");
    (localObject2 = new GridBagConstraints()).anchor = 17;
    ((GridBagConstraints)localObject2).insets = new Insets(0, 5, 5, 5);
    ((GridBagConstraints)localObject2).gridx = 0;
    ((GridBagConstraints)localObject2).gridy = 7;
    add((Component)localObject1, localObject2);
    localObject1 = new class_537(class_949.field_1248);
    (localObject2 = new GridBagConstraints()).insets = new Insets(0, 0, 5, 0);
    ((GridBagConstraints)localObject2).fill = 2;
    ((GridBagConstraints)localObject2).gridx = 1;
    ((GridBagConstraints)localObject2).gridy = 7;
    add((Component)localObject1, localObject2);
    localObject1 = new JLabel(" HiRes Background:");
    (localObject2 = new GridBagConstraints()).insets = new Insets(0, 5, 5, 5);
    ((GridBagConstraints)localObject2).anchor = 17;
    ((GridBagConstraints)localObject2).gridx = 0;
    ((GridBagConstraints)localObject2).gridy = 8;
    add((Component)localObject1, localObject2);
    localObject1 = new class_537(class_949.field_1246);
    (localObject2 = new GridBagConstraints()).insets = new Insets(0, 0, 5, 0);
    ((GridBagConstraints)localObject2).fill = 2;
    ((GridBagConstraints)localObject2).gridx = 1;
    ((GridBagConstraints)localObject2).gridy = 8;
    add((Component)localObject1, localObject2);
    localObject1 = new JLabel(" Tutorial:");
    (localObject2 = new GridBagConstraints()).anchor = 17;
    ((GridBagConstraints)localObject2).insets = new Insets(0, 5, 5, 5);
    ((GridBagConstraints)localObject2).gridx = 0;
    ((GridBagConstraints)localObject2).gridy = 9;
    add((Component)localObject1, localObject2);
    localObject1 = new class_537(class_949.field_1232);
    (localObject2 = new GridBagConstraints()).insets = new Insets(0, 0, 5, 0);
    ((GridBagConstraints)localObject2).fill = 2;
    ((GridBagConstraints)localObject2).gridx = 1;
    ((GridBagConstraints)localObject2).gridy = 9;
    add((Component)localObject1, localObject2);
    localObject1 = new JLabel(" Invert Ship Mouse:");
    (localObject2 = new GridBagConstraints()).anchor = 17;
    ((GridBagConstraints)localObject2).insets = new Insets(0, 5, 5, 5);
    ((GridBagConstraints)localObject2).gridx = 0;
    ((GridBagConstraints)localObject2).gridy = 10;
    add((Component)localObject1, localObject2);
    localObject1 = new class_537(class_949.field_1243);
    (localObject2 = new GridBagConstraints()).fill = 2;
    ((GridBagConstraints)localObject2).insets = new Insets(0, 0, 5, 0);
    ((GridBagConstraints)localObject2).gridx = 1;
    ((GridBagConstraints)localObject2).gridy = 10;
    add((Component)localObject1, localObject2);
    localObject1 = new JLabel(" Invert Mouse for everything:");
    (localObject2 = new GridBagConstraints()).anchor = 13;
    ((GridBagConstraints)localObject2).insets = new Insets(0, 5, 5, 5);
    ((GridBagConstraints)localObject2).gridx = 0;
    ((GridBagConstraints)localObject2).gridy = 11;
    add((Component)localObject1, localObject2);
    localObject1 = new class_537(class_949.field_1244);
    (localObject2 = new GridBagConstraints()).insets = new Insets(0, 0, 5, 0);
    ((GridBagConstraints)localObject2).fill = 2;
    ((GridBagConstraints)localObject2).gridx = 1;
    ((GridBagConstraints)localObject2).gridy = 11;
    add((Component)localObject1, localObject2);
    localObject1 = new JLabel(" Window Pos:");
    (localObject2 = new GridBagConstraints()).anchor = 17;
    ((GridBagConstraints)localObject2).insets = new Insets(0, 5, 5, 5);
    ((GridBagConstraints)localObject2).gridx = 0;
    ((GridBagConstraints)localObject2).gridy = 12;
    add((Component)localObject1, localObject2);
    localObject1 = new class_537(class_949.field_1224);
    (localObject2 = new GridBagConstraints()).insets = new Insets(0, 0, 5, 0);
    ((GridBagConstraints)localObject2).fill = 2;
    ((GridBagConstraints)localObject2).gridx = 1;
    ((GridBagConstraints)localObject2).gridy = 12;
    add((Component)localObject1, localObject2);
    localObject1 = new JLabel(" Enable Background: ");
    (localObject2 = new GridBagConstraints()).anchor = 17;
    ((GridBagConstraints)localObject2).insets = new Insets(0, 5, 5, 5);
    ((GridBagConstraints)localObject2).gridx = 0;
    ((GridBagConstraints)localObject2).gridy = 13;
    add((Component)localObject1, localObject2);
    localObject1 = new class_537(class_949.field_1197);
    (localObject2 = new GridBagConstraints()).insets = new Insets(0, 0, 5, 0);
    ((GridBagConstraints)localObject2).fill = 2;
    ((GridBagConstraints)localObject2).gridx = 1;
    ((GridBagConstraints)localObject2).gridy = 13;
    add((Component)localObject1, localObject2);
    localObject1 = new JLabel(" Enable Shieldhit graphics: ");
    (localObject2 = new GridBagConstraints()).insets = new Insets(0, 5, 5, 5);
    ((GridBagConstraints)localObject2).anchor = 17;
    ((GridBagConstraints)localObject2).gridx = 0;
    ((GridBagConstraints)localObject2).gridy = 14;
    add((Component)localObject1, localObject2);
    localObject1 = new class_537(class_949.field_1195);
    (localObject2 = new GridBagConstraints()).insets = new Insets(0, 0, 5, 0);
    ((GridBagConstraints)localObject2).fill = 2;
    ((GridBagConstraints)localObject2).gridx = 1;
    ((GridBagConstraints)localObject2).gridy = 14;
    add((Component)localObject1, localObject2);
    localObject1 = new JLabel(" Enable Sound: ");
    (localObject2 = new GridBagConstraints()).anchor = 17;
    ((GridBagConstraints)localObject2).insets = new Insets(0, 5, 5, 5);
    ((GridBagConstraints)localObject2).gridx = 0;
    ((GridBagConstraints)localObject2).gridy = 15;
    add((Component)localObject1, localObject2);
    localObject1 = new class_537(class_949.field_1181);
    (localObject2 = new GridBagConstraints()).insets = new Insets(0, 0, 5, 0);
    ((GridBagConstraints)localObject2).fill = 2;
    ((GridBagConstraints)localObject2).gridx = 1;
    ((GridBagConstraints)localObject2).gridy = 15;
    add((Component)localObject1, localObject2);
    localObject1 = new JLabel(" Sound Volume: ");
    (localObject2 = new GridBagConstraints()).anchor = 17;
    ((GridBagConstraints)localObject2).insets = new Insets(0, 5, 5, 5);
    ((GridBagConstraints)localObject2).gridx = 0;
    ((GridBagConstraints)localObject2).gridy = 16;
    add((Component)localObject1, localObject2);
    localObject1 = new class_537(class_949.field_1183);
    (localObject2 = new GridBagConstraints()).insets = new Insets(0, 0, 5, 0);
    ((GridBagConstraints)localObject2).fill = 2;
    ((GridBagConstraints)localObject2).gridx = 1;
    ((GridBagConstraints)localObject2).gridy = 16;
    add((Component)localObject1, localObject2);
    localObject1 = new JLabel(" Field of View (FOV): ");
    (localObject2 = new GridBagConstraints()).anchor = 17;
    ((GridBagConstraints)localObject2).insets = new Insets(0, 5, 5, 5);
    ((GridBagConstraints)localObject2).gridx = 0;
    ((GridBagConstraints)localObject2).gridy = 17;
    add((Component)localObject1, localObject2);
    localObject1 = new class_537(class_949.field_1180);
    (localObject2 = new GridBagConstraints()).insets = new Insets(0, 0, 5, 0);
    ((GridBagConstraints)localObject2).fill = 2;
    ((GridBagConstraints)localObject2).gridx = 1;
    ((GridBagConstraints)localObject2).gridy = 17;
    add((Component)localObject1, localObject2);
    localObject1 = new JLabel(" Use Frame Buffer: ");
    (localObject2 = new GridBagConstraints()).anchor = 17;
    ((GridBagConstraints)localObject2).insets = new Insets(0, 5, 5, 5);
    ((GridBagConstraints)localObject2).gridx = 0;
    ((GridBagConstraints)localObject2).gridy = 18;
    add((Component)localObject1, localObject2);
    localObject1 = new class_537(class_949.field_1206);
    (localObject2 = new GridBagConstraints()).insets = new Insets(0, 0, 5, 0);
    ((GridBagConstraints)localObject2).fill = 2;
    ((GridBagConstraints)localObject2).gridx = 1;
    ((GridBagConstraints)localObject2).gridy = 18;
    add((Component)localObject1, localObject2);
    localObject1 = new JLabel(" Atmosphere Shader: ");
    (localObject2 = new GridBagConstraints()).anchor = 17;
    ((GridBagConstraints)localObject2).insets = new Insets(0, 5, 0, 5);
    ((GridBagConstraints)localObject2).gridx = 0;
    ((GridBagConstraints)localObject2).gridy = 19;
    add((Component)localObject1, localObject2);
    localObject1 = new class_537(class_949.field_1194);
    (localObject2 = new GridBagConstraints()).fill = 2;
    ((GridBagConstraints)localObject2).gridx = 1;
    ((GridBagConstraints)localObject2).gridy = 19;
    add((Component)localObject1, localObject2);
  }
}


/* Location:           C:\Users\Raul\Desktop\StarMadeDec\StarMadeR.zip
 * Qualified Name:     class_583
 * JD-Core Version:    0.7.0-SNAPSHOT-20130630
 */