import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.LayoutManager;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JRootPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.border.EmptyBorder;
import javax.swing.border.TitledBorder;

public final class class_1310
  extends JDialog
{
  private final JPanel jdField_field_1485_of_type_JavaxSwingJPanel = new JPanel();
  private JTextField jdField_field_1485_of_type_JavaxSwingJTextField;
  private class_1316 jdField_field_1485_of_type_Class_1316;
  private final ButtonGroup jdField_field_1485_of_type_JavaxSwingButtonGroup = new ButtonGroup();
  private JCheckBox jdField_field_1485_of_type_JavaxSwingJCheckBox;
  private JCheckBox jdField_field_1486_of_type_JavaxSwingJCheckBox;
  private JRadioButton jdField_field_1485_of_type_JavaxSwingJRadioButton;
  private JRadioButton jdField_field_1486_of_type_JavaxSwingJRadioButton;
  private JRadioButton field_1487;
  
  public class_1310(class_371 paramclass_371)
  {
    super(class_531.field_835, true);
    setDefaultCloseOperation(2);
    setTitle("Change Sector");
    setBounds(100, 100, 541, 251);
    getContentPane().setLayout(new BorderLayout());
    this.jdField_field_1485_of_type_JavaxSwingJPanel.setBorder(new EmptyBorder(5, 5, 5, 5));
    getContentPane().add(this.jdField_field_1485_of_type_JavaxSwingJPanel, "Center");
    (localObject1 = new GridBagLayout()).columnWidths = new int[] { 0, 0, 0 };
    ((GridBagLayout)localObject1).rowHeights = new int[] { 0, 0, 0, 0, 0 };
    ((GridBagLayout)localObject1).columnWeights = new double[] { 0.0D, 1.0D, 4.9E-324D };
    ((GridBagLayout)localObject1).rowWeights = new double[] { 0.0D, 0.0D, 1.0D, 1.0D, 4.9E-324D };
    this.jdField_field_1485_of_type_JavaxSwingJPanel.setLayout((LayoutManager)localObject1);
    (localObject1 = new JLabel("WARNING: Changes made are PERMANENT! Use with care and backup beforehand!")).setForeground(new Color(139, 0, 0));
    Object localObject2;
    (localObject2 = new GridBagConstraints()).anchor = 17;
    ((GridBagConstraints)localObject2).gridwidth = 2;
    ((GridBagConstraints)localObject2).insets = new Insets(0, 0, 5, 5);
    ((GridBagConstraints)localObject2).gridx = 0;
    ((GridBagConstraints)localObject2).gridy = 0;
    this.jdField_field_1485_of_type_JavaxSwingJPanel.add((Component)localObject1, localObject2);
    Object localObject1 = new JLabel("Enter First Letters");
    (localObject2 = new GridBagConstraints()).insets = new Insets(0, 0, 5, 5);
    ((GridBagConstraints)localObject2).anchor = 13;
    ((GridBagConstraints)localObject2).gridx = 0;
    ((GridBagConstraints)localObject2).gridy = 1;
    this.jdField_field_1485_of_type_JavaxSwingJPanel.add((Component)localObject1, localObject2);
    this.jdField_field_1485_of_type_JavaxSwingJTextField = new JTextField();
    (localObject1 = new GridBagConstraints()).insets = new Insets(0, 0, 5, 0);
    ((GridBagConstraints)localObject1).fill = 2;
    ((GridBagConstraints)localObject1).gridx = 1;
    ((GridBagConstraints)localObject1).gridy = 1;
    this.jdField_field_1485_of_type_JavaxSwingJPanel.add(this.jdField_field_1485_of_type_JavaxSwingJTextField, localObject1);
    this.jdField_field_1485_of_type_JavaxSwingJTextField.setColumns(10);
    localObject1 = new JLabel("Options");
    (localObject2 = new GridBagConstraints()).anchor = 17;
    ((GridBagConstraints)localObject2).insets = new Insets(0, 0, 5, 5);
    ((GridBagConstraints)localObject2).gridx = 0;
    ((GridBagConstraints)localObject2).gridy = 2;
    this.jdField_field_1485_of_type_JavaxSwingJPanel.add((Component)localObject1, localObject2);
    localObject1 = new JPanel();
    (localObject2 = new GridBagConstraints()).insets = new Insets(0, 0, 5, 0);
    ((GridBagConstraints)localObject2).fill = 1;
    ((GridBagConstraints)localObject2).gridx = 1;
    ((GridBagConstraints)localObject2).gridy = 2;
    this.jdField_field_1485_of_type_JavaxSwingJPanel.add((Component)localObject1, localObject2);
    (localObject2 = new GridBagLayout()).columnWidths = new int[] { 0, 0, 0, 0 };
    ((GridBagLayout)localObject2).rowHeights = new int[] { 0, 0, 0 };
    ((GridBagLayout)localObject2).columnWeights = new double[] { 0.0D, 0.0D, 0.0D, 4.9E-324D };
    ((GridBagLayout)localObject2).rowWeights = new double[] { 0.0D, 0.0D, 4.9E-324D };
    ((JPanel)localObject1).setLayout((LayoutManager)localObject2);
    this.jdField_field_1485_of_type_JavaxSwingJCheckBox = new JCheckBox("Ships only");
    this.jdField_field_1485_of_type_JavaxSwingJCheckBox.setSelected(true);
    (localObject2 = new GridBagConstraints()).insets = new Insets(0, 0, 5, 5);
    ((GridBagConstraints)localObject2).gridx = 0;
    ((GridBagConstraints)localObject2).gridy = 0;
    ((JPanel)localObject1).add(this.jdField_field_1485_of_type_JavaxSwingJCheckBox, localObject2);
    this.jdField_field_1486_of_type_JavaxSwingJCheckBox = new JCheckBox("All Universe");
    this.jdField_field_1486_of_type_JavaxSwingJCheckBox.addActionListener(new class_1300(this));
    (localObject2 = new GridBagConstraints()).insets = new Insets(0, 0, 5, 5);
    ((GridBagConstraints)localObject2).gridx = 1;
    ((GridBagConstraints)localObject2).gridy = 0;
    ((JPanel)localObject1).add(this.jdField_field_1486_of_type_JavaxSwingJCheckBox, localObject2);
    this.jdField_field_1485_of_type_JavaxSwingJRadioButton = new JRadioButton("Edited Only");
    this.jdField_field_1485_of_type_JavaxSwingButtonGroup.add(this.jdField_field_1485_of_type_JavaxSwingJRadioButton);
    (localObject2 = new GridBagConstraints()).insets = new Insets(0, 0, 0, 5);
    ((GridBagConstraints)localObject2).gridx = 0;
    ((GridBagConstraints)localObject2).gridy = 1;
    ((JPanel)localObject1).add(this.jdField_field_1485_of_type_JavaxSwingJRadioButton, localObject2);
    this.jdField_field_1485_of_type_JavaxSwingJRadioButton.setSelected(true);
    this.jdField_field_1486_of_type_JavaxSwingJRadioButton = new JRadioButton("Unedited Only");
    this.jdField_field_1485_of_type_JavaxSwingButtonGroup.add(this.jdField_field_1486_of_type_JavaxSwingJRadioButton);
    (localObject2 = new GridBagConstraints()).insets = new Insets(0, 0, 0, 5);
    ((GridBagConstraints)localObject2).gridx = 1;
    ((GridBagConstraints)localObject2).gridy = 1;
    ((JPanel)localObject1).add(this.jdField_field_1486_of_type_JavaxSwingJRadioButton, localObject2);
    this.field_1487 = new JRadioButton("Edited & Unedited");
    this.jdField_field_1485_of_type_JavaxSwingButtonGroup.add(this.field_1487);
    (localObject2 = new GridBagConstraints()).gridx = 2;
    ((GridBagConstraints)localObject2).gridy = 1;
    ((JPanel)localObject1).add(this.field_1487, localObject2);
    (localObject1 = new JPanel()).setBorder(new TitledBorder(UIManager.getBorder("TitledBorder.border"), "Sector", 4, 2, null, new Color(0, 0, 0)));
    (localObject2 = new GridBagConstraints()).fill = 1;
    ((GridBagConstraints)localObject2).gridwidth = 2;
    ((GridBagConstraints)localObject2).gridx = 0;
    ((GridBagConstraints)localObject2).gridy = 3;
    this.jdField_field_1485_of_type_JavaxSwingJPanel.add((Component)localObject1, localObject2);
    (localObject2 = new GridBagLayout()).columnWidths = new int[] { 0, 0, 0 };
    ((GridBagLayout)localObject2).rowHeights = new int[] { 0, 0 };
    ((GridBagLayout)localObject2).columnWeights = new double[] { 0.0D, 1.0D, 4.9E-324D };
    ((GridBagLayout)localObject2).rowWeights = new double[] { 0.0D, 4.9E-324D };
    ((JPanel)localObject1).setLayout((LayoutManager)localObject2);
    this.jdField_field_1485_of_type_Class_1316 = new class_1316();
    this.jdField_field_1485_of_type_Class_1316.setMinimumSize(new Dimension(400, 50));
    this.jdField_field_1485_of_type_Class_1316.setPreferredSize(new Dimension(400, 50));
    (localObject2 = new GridBagConstraints()).weightx = 1.0D;
    ((GridBagConstraints)localObject2).anchor = 18;
    ((GridBagConstraints)localObject2).fill = 2;
    ((GridBagConstraints)localObject2).gridwidth = 2;
    ((GridBagConstraints)localObject2).insets = new Insets(0, 0, 0, 5);
    ((GridBagConstraints)localObject2).gridx = 0;
    ((GridBagConstraints)localObject2).gridy = 0;
    ((JPanel)localObject1).add(this.jdField_field_1485_of_type_Class_1316, localObject2);
    (localObject1 = new GridBagLayout()).columnWidths = new int[] { 0 };
    ((GridBagLayout)localObject1).rowHeights = new int[] { 0 };
    ((GridBagLayout)localObject1).columnWeights = new double[] { 4.9E-324D };
    ((GridBagLayout)localObject1).rowWeights = new double[] { 4.9E-324D };
    this.jdField_field_1485_of_type_Class_1316.setLayout((LayoutManager)localObject1);
    (localObject1 = new JPanel()).setLayout(new FlowLayout(2));
    getContentPane().add((Component)localObject1, "South");
    (localObject2 = new JButton("OK")).addActionListener(new class_1298(this, paramclass_371));
    ((JButton)localObject2).setActionCommand("OK");
    ((JPanel)localObject1).add((Component)localObject2);
    getRootPane().setDefaultButton((JButton)localObject2);
    (localObject2 = new JButton("Cancel")).addActionListener(new class_1304(this));
    ((JButton)localObject2).setActionCommand("Cancel");
    ((JPanel)localObject1).add((Component)localObject2);
  }
}


/* Location:           C:\Users\Raul\Desktop\StarMadeDec\StarMadeR.zip
 * Qualified Name:     class_1310
 * JD-Core Version:    0.7.0-SNAPSHOT-20130630
 */