package jo.sm.ui;

import java.awt.Color;
import java.awt.Paint;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

import jo.sm.data.BlockTypes;
import jo.sm.logic.StarMadeLogic;

public class BlockTypeColors
{
    public static final Paint HULL_RED = Color.red;
    
    public static final Map<Short,Color> BLOCK_FILL = new HashMap<Short, Color>();
    static
    {
        BLOCK_FILL.put(BlockTypes.WEAPON_CONTROLLER_ID, Color.red);
        BLOCK_FILL.put(BlockTypes.WEAPON_ID, Color.red);
        BLOCK_FILL.put(BlockTypes.CORE_ID, new Color(.5f, .5f, 1f));
        BLOCK_FILL.put(BlockTypes.DEATHSTAR_CORE_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.GLASS_ID, new Color(.9f, .9f, .9f));
        BLOCK_FILL.put(BlockTypes.THRUSTER_ID, Color.orange);
        BLOCK_FILL.put(BlockTypes.DOCK_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.POWER_ID, Color.blue);
        BLOCK_FILL.put(BlockTypes.SHIELD_ID, Color.cyan);
        BLOCK_FILL.put(BlockTypes.EXPLOSIVE_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.RADAR_JAMMING_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.CLOAKING_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.SALVAGE_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.MISSILE_DUMB_CONTROLLER_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.MISSILE_DUMB_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.MISSILE_HEAT_CONTROLLER_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.MISSILE_HEAT_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.MISSILE_FAFO_CONTROLLER_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.MISSILE_FAFO_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.SALVAGE_CONTROLLER_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.GRAVITY_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.REPAIR_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.REPAIR_CONTROLLER_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.COCKPIT_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.LIGHT_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.LIGHT_BEACON_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_ICE_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.HULL_COLOR_GREY_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.HULL_COLOR_PURPLE_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.HULL_COLOR_BROWN_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.HULL_COLOR_BLACK_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.HULL_COLOR_RED_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.HULL_COLOR_BLUE_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.HULL_COLOR_GREEN_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.HULL_COLOR_YELLOW_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.HULL_COLOR_WHITE_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.LANDING_ELEMENT, Color.gray);
        BLOCK_FILL.put(BlockTypes.LIFT_ELEMENT, Color.gray);
        BLOCK_FILL.put(BlockTypes.RECYCLER_ELEMENT, Color.gray);
        BLOCK_FILL.put(BlockTypes.STASH_ELEMENT, Color.gray);
        BLOCK_FILL.put(BlockTypes.AI_ELEMENT, Color.gray);
        BLOCK_FILL.put(BlockTypes.DOOR_ELEMENT, Color.gray);
        BLOCK_FILL.put(BlockTypes.BUILD_BLOCK_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_LAVA_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_EXOGEN_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_OCTOGEN_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_QUANTAGEN_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_QUANTANIUM_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_PLEXTANIUM_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_ORANGUTANIUM_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_SUCCUMITE_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_CENOMITE_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_AWESOMITE_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_VAPPECIDE_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_MARS_TOP, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_MARS_ROCK, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_MARS_DIRT, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_MARS_TOP_ROCK, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_EXTRANIUM_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_ROCK_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_SAND_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_EARTH_TOP_DIRT, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_EARTH_TOP_ROCK, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_TREE_TRUNK_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_TREE_LEAF_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_WATER, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_DIRT_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.DOCKING_ENHANCER_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_CACTUS_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_PURPLE_ALIEN_TOP, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_PURPLE_ALIEN_ROCK, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_PURPLE_ALIEN_VINE, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_GRASS_SPRITE, Color.gray);
        BLOCK_FILL.put(BlockTypes.PLAYER_SPAWN_MODULE, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_BROWNWEED_SPRITE, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_MARSTENTACLES_SPRITE, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_ALIENVINE_SPRITE, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_GRASSFLOWERS_SPRITE, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_LONGWEED_SPRITE, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_TALLSHROOM_SPRITE, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_PURSPIRE_SPRITE, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_TALLGRASSFLOWERS_SPRITE, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_MINICACTUS_SPRITE, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_REDSHROOM_SPRITE, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_PURPTACLES_SPRITE, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_TALLFLOWERS_SPRITE, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_ROCK_SPRITE, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_ALIENFLOWERS_SPRITE, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_YHOLE_SPRITE, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M1L2_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M1L3_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M1L4_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M1L5_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M2L2_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M2L3_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M2L4_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M2L5_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M3L2_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M3L3_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M3L4_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M3L5_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M4L2_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M4L3_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M4L4_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M4L5_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M5L2_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M5L3_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M5L4_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M5L5_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M6L2_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M6L3_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M6L4_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M6L5_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M7L2_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M7L3_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M7L4_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M7L5_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M8L2_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M8L3_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M8L4_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M8L5_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M9L2_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M9L3_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M9L4_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M9L5_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M10L2_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M10L3_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M10L4_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M10L5_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M11L2_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M11L3_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M11L4_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M11L5_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M12L2_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M12L3_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M12L4_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M12L5_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M13L2_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M13L3_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M13L4_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M13L5_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M14L2_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M14L3_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M14L4_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M14L5_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M15L2_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M15L3_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M15L4_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M15L5_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M16L2_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M16L3_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M16L4_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_M16L5_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_NEGACIDE_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_QUANTACIDE_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_NEGAGATE_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_METATE_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_INSANIUM_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.FACTORY_INPUT_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.FACTORY_INPUT_ENH_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.FACTORY_POWER_CELL_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.FACTORY_POWER_CELL_ENH_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.FACTORY_POWER_COIL_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.FACTORY_POWER_COIL_ENH_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.FACTORY_POWER_BLOCK_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.FACTORY_POWER_BLOCK_ENH_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.POWER_CELL_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.POWER_COIL_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.UNUSED_TEST, Color.gray);
        BLOCK_FILL.put(BlockTypes.FACTORY_PARTICLE_PRESS, Color.gray);
        BLOCK_FILL.put(BlockTypes.MAN_SD1000_CAP, Color.gray);
        BLOCK_FILL.put(BlockTypes.MAN_SD2000_CAP, Color.gray);
        BLOCK_FILL.put(BlockTypes.MAN_SD3000_CAP, Color.gray);
        BLOCK_FILL.put(BlockTypes.MAN_SD1000_FLUX, Color.gray);
        BLOCK_FILL.put(BlockTypes.MAN_SD2000_FLUX, Color.gray);
        BLOCK_FILL.put(BlockTypes.MAN_SD3000_FLUX, Color.gray);
        BLOCK_FILL.put(BlockTypes.MAN_SD1000_MICRO, Color.gray);
        BLOCK_FILL.put(BlockTypes.MAN_SD2000_MICRO, Color.gray);
        BLOCK_FILL.put(BlockTypes.MAN_SD3000_MICRO, Color.gray);
        BLOCK_FILL.put(BlockTypes.MAN_SD1000_DELTA, Color.gray);
        BLOCK_FILL.put(BlockTypes.MAN_SD2000_DELTA, Color.gray);
        BLOCK_FILL.put(BlockTypes.MAN_SD3000_DELTA, Color.gray);
        BLOCK_FILL.put(BlockTypes.MAN_SD1000_MEM, Color.gray);
        BLOCK_FILL.put(BlockTypes.MAN_SD2000_MEM, Color.gray);
        BLOCK_FILL.put(BlockTypes.MAN_SD3000_MEM, Color.gray);
        BLOCK_FILL.put(BlockTypes.MAN_SDPROTON, Color.gray);
        BLOCK_FILL.put(BlockTypes.MAN_RED, Color.gray);
        BLOCK_FILL.put(BlockTypes.MAN_PURP, Color.gray);
        BLOCK_FILL.put(BlockTypes.MAN_BROWN, Color.gray);
        BLOCK_FILL.put(BlockTypes.MAN_GREEN, Color.gray);
        BLOCK_FILL.put(BlockTypes.MAN_YELLOW, Color.gray);
        BLOCK_FILL.put(BlockTypes.MAN_BLACK, Color.gray);
        BLOCK_FILL.put(BlockTypes.MAN_WHITE, Color.gray);
        BLOCK_FILL.put(BlockTypes.MAN_BLUE, Color.gray);
        BLOCK_FILL.put(BlockTypes.MAN_P1000B, Color.gray);
        BLOCK_FILL.put(BlockTypes.MAN_P2000B, Color.gray);
        BLOCK_FILL.put(BlockTypes.MAN_P3000B, Color.gray);
        BLOCK_FILL.put(BlockTypes.MAN_P10000A, Color.gray);
        BLOCK_FILL.put(BlockTypes.MAN_P20000A, Color.gray);
        BLOCK_FILL.put(BlockTypes.MAN_P30000A, Color.gray);
        BLOCK_FILL.put(BlockTypes.MAN_P40000A, Color.gray);
        BLOCK_FILL.put(BlockTypes.MAN_YHOLE_NUC, Color.gray);
        BLOCK_FILL.put(BlockTypes.FACTORY_SD10000, Color.gray);
        BLOCK_FILL.put(BlockTypes.FACTORY_SD20000, Color.gray);
        BLOCK_FILL.put(BlockTypes.FACTORY_SD30000, Color.gray);
        BLOCK_FILL.put(BlockTypes.FACTORY_SDADV, Color.gray);
        BLOCK_FILL.put(BlockTypes.FACTORY_SD1000, Color.gray);
        BLOCK_FILL.put(BlockTypes.FACTORY_SD2000, Color.gray);
        BLOCK_FILL.put(BlockTypes.FACTORY_SD3000, Color.gray);
        BLOCK_FILL.put(BlockTypes.FACTORY_MINERAL, Color.gray);
        BLOCK_FILL.put(BlockTypes.POWERHULL_COLOR_GREY, Color.gray);
        BLOCK_FILL.put(BlockTypes.POWERHULL_COLOR_BLACK, Color.gray);
        BLOCK_FILL.put(BlockTypes.POWERHULL_COLOR_RED, Color.gray);
        BLOCK_FILL.put(BlockTypes.POWERHULL_COLOR_PURPLE, Color.gray);
        BLOCK_FILL.put(BlockTypes.POWERHULL_COLOR_BLUE, Color.gray);
        BLOCK_FILL.put(BlockTypes.POWERHULL_COLOR_GREEN, Color.gray);
        BLOCK_FILL.put(BlockTypes.POWERHULL_COLOR_BROWN, Color.gray);
        BLOCK_FILL.put(BlockTypes.POWERHULL_COLOR_GOLD, Color.gray);
        BLOCK_FILL.put(BlockTypes.POWERHULL_COLOR_WHITE, Color.gray);
        BLOCK_FILL.put(BlockTypes.MAN_GLASS_BOTTLE, Color.gray);
        BLOCK_FILL.put(BlockTypes.MAN_SCIENCE_BOTTLE, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_ICEPLANET_SURFACE, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_ICEPLANET_ROCK, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_ICEPLANET_WOOD, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_ICEPLANET_LEAVES, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_ICEPLANET_SPIKE_SPRITE, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_ICEPLANET_ICECRAG_SPRITE, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_ICEPLANET_ICECORAL_SPRITE, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_ICEPLANET_ICEGRASS_SPRITE, Color.gray);
        BLOCK_FILL.put(BlockTypes.LIGHT_RED, Color.gray);
        BLOCK_FILL.put(BlockTypes.LIGHT_BLUE, Color.gray);
        BLOCK_FILL.put(BlockTypes.LIGHT_GREEN, Color.gray);
        BLOCK_FILL.put(BlockTypes.LIGHT_YELLOW, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_ICEPLANET_CRYSTAL, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_REDWOOD, Color.gray);
        BLOCK_FILL.put(BlockTypes.TERRAIN_REDWOOD_LEAVES, Color.gray);
        BLOCK_FILL.put(BlockTypes.FIXED_DOCK_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.FIXED_DOCK_ID_ENHANCER, Color.gray);
        BLOCK_FILL.put(BlockTypes.FACTION_BLOCK, Color.gray);
        BLOCK_FILL.put(BlockTypes.FACTION_HUB_BLOCK, Color.gray);
        BLOCK_FILL.put(BlockTypes.HULL_COLOR_WEDGE_GREY_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.HULL_COLOR_WEDGE_PURPLE_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.HULL_COLOR_WEDGE_BROWN_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.HULL_COLOR_WEDGE_BLACK_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.HULL_COLOR_WEDGE_RED_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.HULL_COLOR_WEDGE_BLUE_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.HULL_COLOR_WEDGE_GREEN_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.HULL_COLOR_WEDGE_YELLOW_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.HULL_COLOR_WEDGE_WHITE_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.HULL_COLOR_CORNER_GREY_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.HULL_COLOR_CORNER_PURPLE_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.HULL_COLOR_CORNER_BROWN_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.HULL_COLOR_CORNER_BLACK_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.HULL_COLOR_CORNER_RED_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.HULL_COLOR_CORNER_BLUE_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.HULL_COLOR_CORNER_GREEN_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.HULL_COLOR_CORNER_YELLOW_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.HULL_COLOR_CORNER_WHITE_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.POWERHULL_COLOR_WEDGE_GREY, Color.gray);
        BLOCK_FILL.put(BlockTypes.POWERHULL_COLOR_WEDGE_BLACK, Color.gray);
        BLOCK_FILL.put(BlockTypes.POWERHULL_COLOR_WEDGE_RED, Color.gray);
        BLOCK_FILL.put(BlockTypes.POWERHULL_COLOR_WEDGE_PURPLE, Color.gray);
        BLOCK_FILL.put(BlockTypes.POWERHULL_COLOR_WEDGE_BLUE, Color.gray);
        BLOCK_FILL.put(BlockTypes.POWERHULL_COLOR_WEDGE_GREEN, Color.gray);
        BLOCK_FILL.put(BlockTypes.POWERHULL_COLOR_WEDGE_BROWN, Color.gray);
        BLOCK_FILL.put(BlockTypes.POWERHULL_COLOR_WEDGE_GOLD, Color.gray);
        BLOCK_FILL.put(BlockTypes.POWERHULL_COLOR_WEDGE_WHITE, Color.gray);
        BLOCK_FILL.put(BlockTypes.POWERHULL_COLOR_CORNER_GREY, Color.gray);
        BLOCK_FILL.put(BlockTypes.POWERHULL_COLOR_CORNER_BLACK, Color.gray);
        BLOCK_FILL.put(BlockTypes.POWERHULL_COLOR_CORNER_RED, Color.gray);
        BLOCK_FILL.put(BlockTypes.POWERHULL_COLOR_CORNER_PURPLE, Color.gray);
        BLOCK_FILL.put(BlockTypes.POWERHULL_COLOR_CORNER_BLUE, Color.gray);
        BLOCK_FILL.put(BlockTypes.POWERHULL_COLOR_CORNER_GREEN, Color.gray);
        BLOCK_FILL.put(BlockTypes.POWERHULL_COLOR_CORNER_BROWN, Color.gray);
        BLOCK_FILL.put(BlockTypes.POWERHULL_COLOR_CORNER_GOLD, Color.gray);
        BLOCK_FILL.put(BlockTypes.POWERHULL_COLOR_CORNER_WHITE, Color.gray);
        BLOCK_FILL.put(BlockTypes.GLASS_WEDGE_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.GLASS_CORNER_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.POWER_HOLDER_ID, Color.gray);
        BLOCK_FILL.put(BlockTypes.POWER_DRAIN_BEAM_COMPUTER, Color.gray);
        BLOCK_FILL.put(BlockTypes.POWER_DRAIN_BEAM_MODULE, Color.gray);
        BLOCK_FILL.put(BlockTypes.POWER_SUPPLY_BEAM_COMPUTER, Color.gray);
        BLOCK_FILL.put(BlockTypes.POWER_SUPPLY_BEAM_MODULE, Color.gray);
        BLOCK_FILL.put(BlockTypes.DECORATIVE_PANEL_1, Color.gray);
        BLOCK_FILL.put(BlockTypes.DECORATIVE_PANEL_2, Color.gray);
        BLOCK_FILL.put(BlockTypes.DECORATIVE_PANEL_3, Color.gray);
        BLOCK_FILL.put(BlockTypes.DECORATIVE_PANEL_4, Color.gray);
        BLOCK_FILL.put(BlockTypes.LIGHT_BULB_YELLOW, Color.gray);
    }

    public static final Map<Short,Color> BLOCK_OUTLINE = new HashMap<Short, Color>();
    static
    {
        BLOCK_OUTLINE.put(BlockTypes.WEAPON_CONTROLLER_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.WEAPON_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.CORE_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.DEATHSTAR_CORE_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.GLASS_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.THRUSTER_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.DOCK_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.POWER_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.SHIELD_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.EXPLOSIVE_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.RADAR_JAMMING_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.CLOAKING_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.SALVAGE_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.MISSILE_DUMB_CONTROLLER_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.MISSILE_DUMB_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.MISSILE_HEAT_CONTROLLER_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.MISSILE_HEAT_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.MISSILE_FAFO_CONTROLLER_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.MISSILE_FAFO_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.SALVAGE_CONTROLLER_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.GRAVITY_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.REPAIR_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.REPAIR_CONTROLLER_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.COCKPIT_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.LIGHT_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.LIGHT_BEACON_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_ICE_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.HULL_COLOR_GREY_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.HULL_COLOR_PURPLE_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.HULL_COLOR_BROWN_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.HULL_COLOR_BLACK_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.HULL_COLOR_RED_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.HULL_COLOR_BLUE_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.HULL_COLOR_GREEN_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.HULL_COLOR_YELLOW_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.HULL_COLOR_WHITE_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.LANDING_ELEMENT, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.LIFT_ELEMENT, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.RECYCLER_ELEMENT, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.STASH_ELEMENT, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.AI_ELEMENT, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.DOOR_ELEMENT, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.BUILD_BLOCK_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_LAVA_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_EXOGEN_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_OCTOGEN_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_QUANTAGEN_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_QUANTANIUM_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_PLEXTANIUM_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_ORANGUTANIUM_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_SUCCUMITE_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_CENOMITE_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_AWESOMITE_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_VAPPECIDE_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_MARS_TOP, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_MARS_ROCK, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_MARS_DIRT, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_MARS_TOP_ROCK, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_EXTRANIUM_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_ROCK_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_SAND_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_EARTH_TOP_DIRT, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_EARTH_TOP_ROCK, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_TREE_TRUNK_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_TREE_LEAF_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_WATER, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_DIRT_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.DOCKING_ENHANCER_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_CACTUS_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_PURPLE_ALIEN_TOP, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_PURPLE_ALIEN_ROCK, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_PURPLE_ALIEN_VINE, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_GRASS_SPRITE, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.PLAYER_SPAWN_MODULE, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_BROWNWEED_SPRITE, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_MARSTENTACLES_SPRITE, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_ALIENVINE_SPRITE, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_GRASSFLOWERS_SPRITE, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_LONGWEED_SPRITE, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_TALLSHROOM_SPRITE, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_PURSPIRE_SPRITE, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_TALLGRASSFLOWERS_SPRITE, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_MINICACTUS_SPRITE, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_REDSHROOM_SPRITE, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_PURPTACLES_SPRITE, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_TALLFLOWERS_SPRITE, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_ROCK_SPRITE, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_ALIENFLOWERS_SPRITE, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_YHOLE_SPRITE, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M1L2_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M1L3_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M1L4_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M1L5_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M2L2_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M2L3_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M2L4_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M2L5_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M3L2_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M3L3_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M3L4_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M3L5_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M4L2_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M4L3_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M4L4_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M4L5_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M5L2_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M5L3_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M5L4_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M5L5_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M6L2_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M6L3_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M6L4_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M6L5_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M7L2_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M7L3_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M7L4_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M7L5_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M8L2_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M8L3_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M8L4_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M8L5_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M9L2_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M9L3_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M9L4_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M9L5_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M10L2_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M10L3_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M10L4_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M10L5_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M11L2_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M11L3_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M11L4_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M11L5_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M12L2_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M12L3_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M12L4_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M12L5_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M13L2_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M13L3_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M13L4_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M13L5_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M14L2_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M14L3_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M14L4_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M14L5_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M15L2_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M15L3_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M15L4_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M15L5_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M16L2_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M16L3_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M16L4_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_M16L5_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_NEGACIDE_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_QUANTACIDE_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_NEGAGATE_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_METATE_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_INSANIUM_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.FACTORY_INPUT_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.FACTORY_INPUT_ENH_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.FACTORY_POWER_CELL_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.FACTORY_POWER_CELL_ENH_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.FACTORY_POWER_COIL_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.FACTORY_POWER_COIL_ENH_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.FACTORY_POWER_BLOCK_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.FACTORY_POWER_BLOCK_ENH_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.POWER_CELL_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.POWER_COIL_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.UNUSED_TEST, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.FACTORY_PARTICLE_PRESS, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.MAN_SD1000_CAP, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.MAN_SD2000_CAP, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.MAN_SD3000_CAP, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.MAN_SD1000_FLUX, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.MAN_SD2000_FLUX, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.MAN_SD3000_FLUX, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.MAN_SD1000_MICRO, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.MAN_SD2000_MICRO, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.MAN_SD3000_MICRO, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.MAN_SD1000_DELTA, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.MAN_SD2000_DELTA, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.MAN_SD3000_DELTA, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.MAN_SD1000_MEM, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.MAN_SD2000_MEM, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.MAN_SD3000_MEM, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.MAN_SDPROTON, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.MAN_RED, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.MAN_PURP, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.MAN_BROWN, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.MAN_GREEN, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.MAN_YELLOW, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.MAN_BLACK, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.MAN_WHITE, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.MAN_BLUE, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.MAN_P1000B, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.MAN_P2000B, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.MAN_P3000B, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.MAN_P10000A, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.MAN_P20000A, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.MAN_P30000A, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.MAN_P40000A, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.MAN_YHOLE_NUC, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.FACTORY_SD10000, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.FACTORY_SD20000, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.FACTORY_SD30000, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.FACTORY_SDADV, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.FACTORY_SD1000, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.FACTORY_SD2000, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.FACTORY_SD3000, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.FACTORY_MINERAL, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.POWERHULL_COLOR_GREY, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.POWERHULL_COLOR_BLACK, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.POWERHULL_COLOR_RED, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.POWERHULL_COLOR_PURPLE, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.POWERHULL_COLOR_BLUE, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.POWERHULL_COLOR_GREEN, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.POWERHULL_COLOR_BROWN, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.POWERHULL_COLOR_GOLD, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.POWERHULL_COLOR_WHITE, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.MAN_GLASS_BOTTLE, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.MAN_SCIENCE_BOTTLE, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_ICEPLANET_SURFACE, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_ICEPLANET_ROCK, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_ICEPLANET_WOOD, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_ICEPLANET_LEAVES, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_ICEPLANET_SPIKE_SPRITE, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_ICEPLANET_ICECRAG_SPRITE, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_ICEPLANET_ICECORAL_SPRITE, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_ICEPLANET_ICEGRASS_SPRITE, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.LIGHT_RED, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.LIGHT_BLUE, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.LIGHT_GREEN, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.LIGHT_YELLOW, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_ICEPLANET_CRYSTAL, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_REDWOOD, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.TERRAIN_REDWOOD_LEAVES, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.FIXED_DOCK_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.FIXED_DOCK_ID_ENHANCER, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.FACTION_BLOCK, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.FACTION_HUB_BLOCK, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.HULL_COLOR_WEDGE_GREY_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.HULL_COLOR_WEDGE_PURPLE_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.HULL_COLOR_WEDGE_BROWN_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.HULL_COLOR_WEDGE_BLACK_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.HULL_COLOR_WEDGE_RED_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.HULL_COLOR_WEDGE_BLUE_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.HULL_COLOR_WEDGE_GREEN_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.HULL_COLOR_WEDGE_YELLOW_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.HULL_COLOR_WEDGE_WHITE_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.HULL_COLOR_CORNER_GREY_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.HULL_COLOR_CORNER_PURPLE_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.HULL_COLOR_CORNER_BROWN_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.HULL_COLOR_CORNER_BLACK_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.HULL_COLOR_CORNER_RED_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.HULL_COLOR_CORNER_BLUE_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.HULL_COLOR_CORNER_GREEN_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.HULL_COLOR_CORNER_YELLOW_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.HULL_COLOR_CORNER_WHITE_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.POWERHULL_COLOR_WEDGE_GREY, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.POWERHULL_COLOR_WEDGE_BLACK, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.POWERHULL_COLOR_WEDGE_RED, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.POWERHULL_COLOR_WEDGE_PURPLE, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.POWERHULL_COLOR_WEDGE_BLUE, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.POWERHULL_COLOR_WEDGE_GREEN, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.POWERHULL_COLOR_WEDGE_BROWN, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.POWERHULL_COLOR_WEDGE_GOLD, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.POWERHULL_COLOR_WEDGE_WHITE, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.POWERHULL_COLOR_CORNER_GREY, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.POWERHULL_COLOR_CORNER_BLACK, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.POWERHULL_COLOR_CORNER_RED, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.POWERHULL_COLOR_CORNER_PURPLE, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.POWERHULL_COLOR_CORNER_BLUE, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.POWERHULL_COLOR_CORNER_GREEN, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.POWERHULL_COLOR_CORNER_BROWN, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.POWERHULL_COLOR_CORNER_GOLD, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.POWERHULL_COLOR_CORNER_WHITE, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.GLASS_WEDGE_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.GLASS_CORNER_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.POWER_HOLDER_ID, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.POWER_DRAIN_BEAM_COMPUTER, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.POWER_DRAIN_BEAM_MODULE, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.POWER_SUPPLY_BEAM_COMPUTER, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.POWER_SUPPLY_BEAM_MODULE, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.DECORATIVE_PANEL_1, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.DECORATIVE_PANEL_2, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.DECORATIVE_PANEL_3, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.DECORATIVE_PANEL_4, Color.white);
        BLOCK_OUTLINE.put(BlockTypes.LIGHT_BULB_YELLOW, Color.white);
    }

    public static Color getOutlineColor(short blockType)
    {
        if (BLOCK_OUTLINE.containsKey(blockType))
            return BLOCK_OUTLINE.get(blockType);
        return Color.white;
    }

    public static Color getFillColor(short blockType)
    {
        if (BLOCK_FILL.containsKey(blockType))
            return BLOCK_FILL.get(blockType);
        return Color.gray;
    }
    

    public static final Map<Short,Integer> BLOCK_ICON = new HashMap<Short, Integer>();
    static
    {
        BLOCK_ICON.put(BlockTypes.HULL_COLOR_GREY_ID, 16);
        BLOCK_ICON.put(BlockTypes.HULL_COLOR_BLACK_ID, 17);
        BLOCK_ICON.put(BlockTypes.HULL_COLOR_RED_ID, 18);
        BLOCK_ICON.put(BlockTypes.HULL_COLOR_PURPLE_ID, 19);
        BLOCK_ICON.put(BlockTypes.HULL_COLOR_BLUE_ID, 20);
        BLOCK_ICON.put(BlockTypes.HULL_COLOR_GREEN_ID, 21);
        BLOCK_ICON.put(BlockTypes.HULL_COLOR_BROWN_ID, 22);
        BLOCK_ICON.put(BlockTypes.HULL_COLOR_YELLOW_ID, 23);
        BLOCK_ICON.put(BlockTypes.HULL_COLOR_WHITE_ID, 24);
    }
    
    private static boolean     mBlockIconsLoaded = false;
    private static ImageIcon[] mBlockIcons;

    public static ImageIcon getBlockImage(short blockID)
    {
        if (!BLOCK_ICON.containsKey(blockID))
            return null;
        if (!mBlockIconsLoaded)
        {
            try
            {
                mBlockIcons = new ImageIcon[768];
                BufferedImage[] localObject = new BufferedImage[3];
                localObject[0] = ImageIO.read(new File(
                        StarMadeLogic.getInstance().getBaseDir(),
                        "data/textures/block/t000.png"));
                localObject[1] = ImageIO.read(new File(
                        StarMadeLogic.getInstance().getBaseDir(),
                        "/data/textures/block/t001.png"));
                localObject[2] = ImageIO.read(new File(
                        StarMadeLogic.getInstance().getBaseDir(),
                        "/data/textures/block/t002.png"));
                for (int i = 0; i < mBlockIcons.length; i++)
                {
                    int j = i % 256 % 16;
                    int k = i % 256 / 16;
                    BufferedImage localBufferedImage = localObject[(i / 256)]
                            .getSubimage(j << 6, k << 6, 64, 64);
                    mBlockIcons[i] = new ImageIcon(localBufferedImage);
                }
            }
            catch (IOException e)
            {
                e.printStackTrace();
            }
            mBlockIconsLoaded = true;
        }
        if (mBlockIcons == null)
            return null;
        return mBlockIcons[BLOCK_ICON.get(blockID)];
    }
}
